import pytest
import sys
from unittest.mock import patch
from pathlib import Path
from aaa.init_commands import interactive

# GOLDEN MASTER SNAPSHOT
EXPECTED_YAML = """metadata:
  name: golden-policy
  version: 1.0.0
rules:
- id: rule1
  description: desc1
  severity: high
  check:
    type: file_exists
    path: README.md
"""

EXPECTED_PY = """# Generated by AAA Governance Compiler v1.3
# Policy: golden-policy (v1.0.0)
import sys
from pathlib import Path
import json
import re

# --- Helper Functions ---

def check_file_exists(path: str) -> bool:
    return Path(path).exists()

def check_content_contains(path: str, pattern: str) -> bool:
    p = Path(path)
    if not p.exists(): return False
    content = p.read_text(encoding='utf-8')
    return re.search(pattern, content) is not None

def check_json_match(path: str, key_path: str, expected) -> bool:
    p = Path(path)
    if not p.exists(): return False
    try:
        data = json.loads(p.read_text(encoding='utf-8'))
        keys = key_path.split('.')
        val = data
        for k in keys:
            if isinstance(val, dict): val = val.get(k)
            else: return False
        return val == expected
    except:
        return False


def main():
    violations = []
    print('Running Policy: golden-policy')
    # Rule: rule1
    if not check_file_exists('README.md'):
        violations.append({'id': 'rule1', 'severity': 'high', 'message': 'File not found: README.md'})

    if violations:
        print('\\n❌ Policy Violations Found:')
        for v in violations:
            print(f'  - [{v["severity"]}] {v["id"]}: {v["message"]}')
        sys.exit(1)
    else:
        print('\\n✅ All checks passed.')
        sys.exit(0)

if __name__ == '__main__':
    main()"""

def test_interactive_snapshot(tmp_path):
    with patch("aaa.init_commands.typer") as mock_typer:
        # User Sequence
        mock_typer.prompt.side_effect = [
            "golden-policy", # Name
            "1.0.0",         # Version
            "rule1",         # ID
            "desc1",         # Desc
            "file_exists",   # Type
            "README.md",     # Path
            "high",          # Severity
        ]
        mock_typer.confirm.side_effect = [
            True,  # Add rule
            False, # Stop adding rules
            True   # Compile
        ]
        
        output_dir = tmp_path / "snapshot_out"
        interactive(output_dir=output_dir)
        
        # Verify content matches Golden Master EXACTLY
        yaml_content = (output_dir / "golden-policy.yaml").read_text()
        py_content = (output_dir / "check_golden_policy.py").read_text()
        
        # Normalize line endings if needed, but strict string match is preferred for snapshots
        assert yaml_content.strip() == EXPECTED_YAML.strip()
        assert py_content.strip() == EXPECTED_PY.strip()
