import os
import json
import datetime
import subprocess
from pathlib import Path
from typing import Any, Dict, List

def get_git_author() -> str:
    try:
        result = subprocess.run(
            ["git", "config", "user.name"], 
            capture_output=True, 
            text=True, 
            check=False
        )
        return result.stdout.strip() or "Unknown Author"
    except Exception:
        return "Unknown Author"

def get_git_logs(count: int = 50) -> str:
    try:
        # 獲取最近 N 筆 commits，過濾 feat/fix/docs
        cmd = ["git", "log", "-n", str(count), "--pretty=format:- %h: %s"]
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            return "No git logs found or not a git repository."
        
        logs = result.stdout.splitlines()
        filtered = [line for line in logs if any(x in line.lower() for x in ["feat", "fix", "docs"])]
        return "\n".join(filtered) if filtered else "No matching feat/fix/docs commits found."
    except Exception as e:
        return f"Error mining git logs: {str(e)}"

def init_milestone(milestone_id: str, workspace_root: Path) -> Dict[str, Any]:
    milestone_dir = workspace_root / "internal/development/milestones" / milestone_id
    
    if milestone_dir.exists():
        return {
            "status": "skipped_or_warned",
            "message": f"Milestone directory {milestone_id} already exists."
        }
    
    try:
        milestone_dir.mkdir(parents=True)
        
        template_path = workspace_root / "templates" / "PRD-template.md"
        target_path = milestone_dir / "PRD.md"
        
        if template_path.exists():
            content = template_path.read_text()
            author = get_git_author()
            today = datetime.date.today().isoformat()
            
            content = content.replace("<AUTHOR>", author)
            content = content.replace("<DATE>", today)
            content = content.replace("<STATUS>", "Draft")
            
            target_path.write_text(content)
        
        # Registration (Upgraded to Dict structure)
        index_path = workspace_root / "internal" / "index.json"
        index_data = {"milestones": []}
        
        if index_path.exists():
            try:
                index_data = json.loads(index_path.read_text())
            except json.JSONDecodeError:
                pass
        else:
            index_path.parent.mkdir(parents=True, exist_ok=True)
            
        milestone_entry = {
            "id": milestone_id,
            "status": "active",
            "created_at": datetime.datetime.now().isoformat()
        }
        
        if "milestones" not in index_data:
            index_data["milestones"] = []
            
        # Check if already in list (handling both str and dict formats for backward compatibility)
        ids = [m if isinstance(m, str) else m.get("id") for m in index_data["milestones"]]
        if milestone_id not in ids:
            index_data["milestones"].append(milestone_entry)
            index_path.write_text(json.dumps(index_data, indent=2))
            
        return {
            "status": "success",
            "message": f"Milestone {milestone_id} initialized successfully."
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}

def complete_milestone(milestone_id: str, workspace_root: Path) -> Dict[str, Any]:
    milestone_dir = workspace_root / "internal/development/milestones" / milestone_id
    report_path = milestone_dir / "completion_report.md"
    
    try:
        # 1. Evidence Collection (Git Logs)
        git_logs = get_git_logs()
        
        # 2. Render Completion Report
        today = datetime.date.today().isoformat()
        report_content = [
            f"# {milestone_id} Completion Report",
            "",
            f"**Status**: Completed  ",
            f"**Completion Date**: {today}  ",
            "",
            "## Evidence Collection",
            "",
            "### Git Commits (feat/fix/docs)",
            git_logs,
            "",
            "## Test Coverage Appendix",
            "",
            "TODO: Run 'aaa check' to populate test results.",
            "",
            "---",
            f"Generated by AAA Milestone Manager at {datetime.datetime.now().isoformat()}"
        ]
        
        report_path.write_text("\n".join(report_content))
        
        # 3. Update index.json status
        index_path = workspace_root / "internal" / "index.json"
        if index_path.exists():
            data = json.loads(index_path.read_text())
            updated = False
            for m in data.get("milestones", []):
                if isinstance(m, dict) and m.get("id") == milestone_id:
                    m["status"] = "completed"
                    m["completed_at"] = datetime.datetime.now().isoformat()
                    updated = True
                    break
            if updated:
                index_path.write_text(json.dumps(data, indent=2))
                
        return {
            "status": "success",
            "message": f"Milestone {milestone_id} completed. Report generated at {report_path}."
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
